2021-03-31 19:58:15.721 - INFO - 4431 - azureml.train.automl.automlconfig._start_execution:206 - Submitting remote.
2021-03-31 20:46:27.716 - INFO - 4431 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-03-31 20:46:27.823 - INFO - 4431 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-03-31 20:46:27.846 - INFO - 4431 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2021-03-31 20:46:27.978 - INFO - 4431 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=132.6[ms]
2021-03-31 20:46:28.038 - INFO - 4431 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=215.01[ms]
2021-03-31 20:46:28.059 - INFO - 4431 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2021-03-31 20:46:44.211 - INFO - 4431 - azureml.automl.runtime.distributed.utilities.horovod_initialized:58 - Horovod not found in current environment. Distribution via Horovod will be disabled.
2021-03-31 20:46:48.592 - INFO - 4431 - azureml.automl.runtime.featurization.data_transformer.__init__:174 - Feature sweeping enabled: False
2021-03-31 20:46:48.603 - INFO - 4431 - azureml.automl.runtime.featurization.data_transformer.__init__:175 - Feature sweeping timeout: 86400
2021-03-31 20:46:52.262 - CRITICAL - 4431 - azureml.train.automl._model_download_utilities.log_traceback:224 - Type: Unclassified
Class: XGBoostError
Message: [20:46:52] /mnt/xgboost/src/learner.cc:922: Check failed: header == serialisation_header_: 

  If you are loading a serialized model (like pickle in Python) generated by older
  XGBoost, please export the model by calling `Booster.save_model` from that version
  first, then load it back in current version.  There's a simple script for helping
  the process. See:

    https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html

  for reference to the script, and more details about differences between saving model and
  serializing.


Stack trace:
  [bt] (0) /anaconda/envs/azureml_py36/lib/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x7c) [0x7fc699ba264c]
  [bt] (1) /anaconda/envs/azureml_py36/lib/libxgboost.so(xgboost::LearnerIO::Load(dmlc::Stream*)+0x66b) [0x7fc699cacf0b]
  [bt] (2) /anaconda/envs/azureml_py36/lib/libxgboost.so(XGBoosterUnserializeFromBuffer+0x5e) [0x7fc699b967fe]
  [bt] (3) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x69dd) [0x7fc7a48729dd]
  [bt] (4) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x6067) [0x7fc7a4872067]
  [bt] (5) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fc7a488aede]
  [bt] (6) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fc7a488b915]
  [bt] (7) /anaconda/envs/azureml_py36/bin/python(_PyObject_FastCallDict+0x8b) [0x564f6a599e3b]
  [bt] (8) /anaconda/envs/azureml_py36/bin/python(+0x199c0e) [0x564f6a621c0e]


Traceback:
  File "_model_download_utilities.py", line 177, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "core.py", line 1088, in __setstate__
    _LIB.XGBoosterUnserializeFromBuffer(handle, ptr, length))
  File "core.py", line 189, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))

ExceptionTarget: Unspecified
2021-03-31 20:46:52.307 - CRITICAL - 4431 - azureml.train.automl._model_download_utilities.log_traceback:224 - Type: IncompatibleOrMissingDependency
Class: ConfigException
Message: ConfigException:
	Message: The model you attempted to retrieve requires 'xgboost' to be installed at '==0.90'. You have 'xgboost==1.3.3', please reinstall 'xgboost==0.90' (e.g. `pip install xgboost==0.90`) and rerun the previous command.
	InnerException: XGBoostError: [20:46:52] /mnt/xgboost/src/learner.cc:922: Check failed: header == serialisation_header_: 

  If you are loading a serialized model (like pickle in Python) generated by older
  XGBoost, please export the model by calling `Booster.save_model` from that version
  first, then load it back in current version.  There's a simple script for helping
  the process. See:

    https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html

  for reference to the script, and more details about differences between saving model and
  serializing.


Stack trace:
  [bt] (0) /anaconda/envs/azureml_py36/lib/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x7c) [0x7fc699ba264c]
  [bt] (1) /anaconda/envs/azureml_py36/lib/libxgboost.so(xgboost::LearnerIO::Load(dmlc::Stream*)+0x66b) [0x7fc699cacf0b]
  [bt] (2) /anaconda/envs/azureml_py36/lib/libxgboost.so(XGBoosterUnserializeFromBuffer+0x5e) [0x7fc699b967fe]
  [bt] (3) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x69dd) [0x7fc7a48729dd]
  [bt] (4) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x6067) [0x7fc7a4872067]
  [bt] (5) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fc7a488aede]
  [bt] (6) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fc7a488b915]
  [bt] (7) /anaconda/envs/azureml_py36/bin/python(_PyObject_FastCallDict+0x8b) [0x564f6a599e3b]
  [bt] (8) /anaconda/envs/azureml_py36/bin/python(+0x199c0e) [0x564f6a621c0e]


	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "The model you attempted to retrieve requires 'xgboost' to be installed at '==0.90'. You have 'xgboost==1.3.3', please reinstall 'xgboost==0.90' (e.g. `pip install xgboost==0.90`) and rerun the previous command.",
        "target": "get_output",
        "inner_error": {
            "code": "NotSupported",
            "inner_error": {
                "code": "IncompatibleOrMissingDependency"
            }
        },
        "reference_code": "910310e6-2433-40cd-b597-9ec2950bc1d8"
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "_model_download_utilities.py", line 91, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 281, in _load_automl_model
    ) from e

ExceptionTarget: get_output
2021-03-31 20:46:52.320 - INFO - 4431 - azureml.train.automl._model_download_utilities._log_activity:93 - ActivityCompleted: Activity=DownloadModel, HowEnded=Failure, Duration=24261.16[ms]
2021-03-31 20:46:52.321 - CRITICAL - 4431 - azureml.train.automl.run.log_traceback:224 - Type: IncompatibleOrMissingDependency
Class: ConfigException
Message: ConfigException:
	Message: The model you attempted to retrieve requires 'xgboost' to be installed at '==0.90'. You have 'xgboost==1.3.3', please reinstall 'xgboost==0.90' (e.g. `pip install xgboost==0.90`) and rerun the previous command.
	InnerException: XGBoostError: [20:46:52] /mnt/xgboost/src/learner.cc:922: Check failed: header == serialisation_header_: 

  If you are loading a serialized model (like pickle in Python) generated by older
  XGBoost, please export the model by calling `Booster.save_model` from that version
  first, then load it back in current version.  There's a simple script for helping
  the process. See:

    https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html

  for reference to the script, and more details about differences between saving model and
  serializing.


Stack trace:
  [bt] (0) /anaconda/envs/azureml_py36/lib/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x7c) [0x7fc699ba264c]
  [bt] (1) /anaconda/envs/azureml_py36/lib/libxgboost.so(xgboost::LearnerIO::Load(dmlc::Stream*)+0x66b) [0x7fc699cacf0b]
  [bt] (2) /anaconda/envs/azureml_py36/lib/libxgboost.so(XGBoosterUnserializeFromBuffer+0x5e) [0x7fc699b967fe]
  [bt] (3) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x69dd) [0x7fc7a48729dd]
  [bt] (4) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x6067) [0x7fc7a4872067]
  [bt] (5) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fc7a488aede]
  [bt] (6) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fc7a488b915]
  [bt] (7) /anaconda/envs/azureml_py36/bin/python(_PyObject_FastCallDict+0x8b) [0x564f6a599e3b]
  [bt] (8) /anaconda/envs/azureml_py36/bin/python(+0x199c0e) [0x564f6a621c0e]


	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "The model you attempted to retrieve requires 'xgboost' to be installed at '==0.90'. You have 'xgboost==1.3.3', please reinstall 'xgboost==0.90' (e.g. `pip install xgboost==0.90`) and rerun the previous command.",
        "target": "get_output",
        "inner_error": {
            "code": "NotSupported",
            "inner_error": {
                "code": "IncompatibleOrMissingDependency"
            }
        },
        "reference_code": "910310e6-2433-40cd-b597-9ec2950bc1d8"
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 704, in get_output
    fitted_model = _download_automl_model(curr_run, model_name)
  File "_model_download_utilities.py", line 91, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 281, in _load_automl_model
    ) from e

ExceptionTarget: get_output
2021-03-31 20:46:52.322 - INFO - 4431 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=24605.86[ms]
2021-03-31 20:48:29.105 - INFO - 4431 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-03-31 20:48:29.120 - INFO - 4431 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-03-31 20:48:29.130 - INFO - 4431 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2021-03-31 20:48:29.279 - INFO - 4431 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=149.69[ms]
2021-03-31 20:48:29.359 - INFO - 4431 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=239.12[ms]
2021-03-31 20:48:29.359 - INFO - 4431 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2021-03-31 20:48:29.984 - INFO - 4431 - azureml.automl.runtime.featurization.data_transformer.__init__:174 - Feature sweeping enabled: False
2021-03-31 20:48:29.984 - INFO - 4431 - azureml.automl.runtime.featurization.data_transformer.__init__:175 - Feature sweeping timeout: 86400
2021-03-31 20:48:29.986 - CRITICAL - 4431 - azureml.train.automl._model_download_utilities.log_traceback:224 - Type: Unclassified
Class: XGBoostError
Message: [20:48:29] /mnt/xgboost/src/learner.cc:922: Check failed: header == serialisation_header_: 

  If you are loading a serialized model (like pickle in Python) generated by older
  XGBoost, please export the model by calling `Booster.save_model` from that version
  first, then load it back in current version.  There's a simple script for helping
  the process. See:

    https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html

  for reference to the script, and more details about differences between saving model and
  serializing.


Stack trace:
  [bt] (0) /anaconda/envs/azureml_py36/lib/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x7c) [0x7fc699ba264c]
  [bt] (1) /anaconda/envs/azureml_py36/lib/libxgboost.so(xgboost::LearnerIO::Load(dmlc::Stream*)+0x66b) [0x7fc699cacf0b]
  [bt] (2) /anaconda/envs/azureml_py36/lib/libxgboost.so(XGBoosterUnserializeFromBuffer+0x5e) [0x7fc699b967fe]
  [bt] (3) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x69dd) [0x7fc7a48729dd]
  [bt] (4) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x6067) [0x7fc7a4872067]
  [bt] (5) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fc7a488aede]
  [bt] (6) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fc7a488b915]
  [bt] (7) /anaconda/envs/azureml_py36/bin/python(_PyObject_FastCallDict+0x8b) [0x564f6a599e3b]
  [bt] (8) /anaconda/envs/azureml_py36/bin/python(+0x199c0e) [0x564f6a621c0e]


Traceback:
  File "_model_download_utilities.py", line 177, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "core.py", line 1088, in __setstate__
    _LIB.XGBoosterUnserializeFromBuffer(handle, ptr, length))
  File "core.py", line 189, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))

ExceptionTarget: Unspecified
2021-03-31 20:48:30.009 - CRITICAL - 4431 - azureml.train.automl._model_download_utilities.log_traceback:224 - Type: IncompatibleOrMissingDependency
Class: ConfigException
Message: ConfigException:
	Message: The model you attempted to retrieve requires 'xgboost' to be installed at '==0.90'. You have 'xgboost==1.3.3', please reinstall 'xgboost==0.90' (e.g. `pip install xgboost==0.90`) and rerun the previous command.
	InnerException: XGBoostError: [20:48:29] /mnt/xgboost/src/learner.cc:922: Check failed: header == serialisation_header_: 

  If you are loading a serialized model (like pickle in Python) generated by older
  XGBoost, please export the model by calling `Booster.save_model` from that version
  first, then load it back in current version.  There's a simple script for helping
  the process. See:

    https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html

  for reference to the script, and more details about differences between saving model and
  serializing.


Stack trace:
  [bt] (0) /anaconda/envs/azureml_py36/lib/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x7c) [0x7fc699ba264c]
  [bt] (1) /anaconda/envs/azureml_py36/lib/libxgboost.so(xgboost::LearnerIO::Load(dmlc::Stream*)+0x66b) [0x7fc699cacf0b]
  [bt] (2) /anaconda/envs/azureml_py36/lib/libxgboost.so(XGBoosterUnserializeFromBuffer+0x5e) [0x7fc699b967fe]
  [bt] (3) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x69dd) [0x7fc7a48729dd]
  [bt] (4) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x6067) [0x7fc7a4872067]
  [bt] (5) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fc7a488aede]
  [bt] (6) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fc7a488b915]
  [bt] (7) /anaconda/envs/azureml_py36/bin/python(_PyObject_FastCallDict+0x8b) [0x564f6a599e3b]
  [bt] (8) /anaconda/envs/azureml_py36/bin/python(+0x199c0e) [0x564f6a621c0e]


	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "The model you attempted to retrieve requires 'xgboost' to be installed at '==0.90'. You have 'xgboost==1.3.3', please reinstall 'xgboost==0.90' (e.g. `pip install xgboost==0.90`) and rerun the previous command.",
        "target": "get_output",
        "inner_error": {
            "code": "NotSupported",
            "inner_error": {
                "code": "IncompatibleOrMissingDependency"
            }
        },
        "reference_code": "910310e6-2433-40cd-b597-9ec2950bc1d8"
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "_model_download_utilities.py", line 91, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 281, in _load_automl_model
    ) from e

ExceptionTarget: get_output
2021-03-31 20:48:30.010 - INFO - 4431 - azureml.train.automl._model_download_utilities._log_activity:93 - ActivityCompleted: Activity=DownloadModel, HowEnded=Failure, Duration=650.4[ms]
2021-03-31 20:48:30.010 - CRITICAL - 4431 - azureml.train.automl.run.log_traceback:224 - Type: IncompatibleOrMissingDependency
Class: ConfigException
Message: ConfigException:
	Message: The model you attempted to retrieve requires 'xgboost' to be installed at '==0.90'. You have 'xgboost==1.3.3', please reinstall 'xgboost==0.90' (e.g. `pip install xgboost==0.90`) and rerun the previous command.
	InnerException: XGBoostError: [20:48:29] /mnt/xgboost/src/learner.cc:922: Check failed: header == serialisation_header_: 

  If you are loading a serialized model (like pickle in Python) generated by older
  XGBoost, please export the model by calling `Booster.save_model` from that version
  first, then load it back in current version.  There's a simple script for helping
  the process. See:

    https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html

  for reference to the script, and more details about differences between saving model and
  serializing.


Stack trace:
  [bt] (0) /anaconda/envs/azureml_py36/lib/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x7c) [0x7fc699ba264c]
  [bt] (1) /anaconda/envs/azureml_py36/lib/libxgboost.so(xgboost::LearnerIO::Load(dmlc::Stream*)+0x66b) [0x7fc699cacf0b]
  [bt] (2) /anaconda/envs/azureml_py36/lib/libxgboost.so(XGBoosterUnserializeFromBuffer+0x5e) [0x7fc699b967fe]
  [bt] (3) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x69dd) [0x7fc7a48729dd]
  [bt] (4) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x6067) [0x7fc7a4872067]
  [bt] (5) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fc7a488aede]
  [bt] (6) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fc7a488b915]
  [bt] (7) /anaconda/envs/azureml_py36/bin/python(_PyObject_FastCallDict+0x8b) [0x564f6a599e3b]
  [bt] (8) /anaconda/envs/azureml_py36/bin/python(+0x199c0e) [0x564f6a621c0e]


	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "The model you attempted to retrieve requires 'xgboost' to be installed at '==0.90'. You have 'xgboost==1.3.3', please reinstall 'xgboost==0.90' (e.g. `pip install xgboost==0.90`) and rerun the previous command.",
        "target": "get_output",
        "inner_error": {
            "code": "NotSupported",
            "inner_error": {
                "code": "IncompatibleOrMissingDependency"
            }
        },
        "reference_code": "910310e6-2433-40cd-b597-9ec2950bc1d8"
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 704, in get_output
    fitted_model = _download_automl_model(curr_run, model_name)
  File "_model_download_utilities.py", line 91, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 281, in _load_automl_model
    ) from e

ExceptionTarget: get_output
2021-03-31 20:48:30.011 - INFO - 4431 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=905.36[ms]
2021-03-31 20:48:51.089 - INFO - 4431 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-03-31 20:48:51.095 - INFO - 4431 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2021-03-31 20:48:51.114 - INFO - 4431 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2021-03-31 20:48:51.259 - INFO - 4431 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=145.56[ms]
2021-03-31 20:48:51.313 - INFO - 4431 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=218.01[ms]
2021-03-31 20:48:51.314 - INFO - 4431 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2021-03-31 20:48:51.777 - INFO - 4431 - azureml.automl.runtime.featurization.data_transformer.__init__:174 - Feature sweeping enabled: False
2021-03-31 20:48:51.778 - INFO - 4431 - azureml.automl.runtime.featurization.data_transformer.__init__:175 - Feature sweeping timeout: 86400
2021-03-31 20:48:51.779 - CRITICAL - 4431 - azureml.train.automl._model_download_utilities.log_traceback:224 - Type: Unclassified
Class: XGBoostError
Message: [20:48:51] /mnt/xgboost/src/learner.cc:922: Check failed: header == serialisation_header_: 

  If you are loading a serialized model (like pickle in Python) generated by older
  XGBoost, please export the model by calling `Booster.save_model` from that version
  first, then load it back in current version.  There's a simple script for helping
  the process. See:

    https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html

  for reference to the script, and more details about differences between saving model and
  serializing.


Stack trace:
  [bt] (0) /anaconda/envs/azureml_py36/lib/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x7c) [0x7fc699ba264c]
  [bt] (1) /anaconda/envs/azureml_py36/lib/libxgboost.so(xgboost::LearnerIO::Load(dmlc::Stream*)+0x66b) [0x7fc699cacf0b]
  [bt] (2) /anaconda/envs/azureml_py36/lib/libxgboost.so(XGBoosterUnserializeFromBuffer+0x5e) [0x7fc699b967fe]
  [bt] (3) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x69dd) [0x7fc7a48729dd]
  [bt] (4) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x6067) [0x7fc7a4872067]
  [bt] (5) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fc7a488aede]
  [bt] (6) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fc7a488b915]
  [bt] (7) /anaconda/envs/azureml_py36/bin/python(_PyObject_FastCallDict+0x8b) [0x564f6a599e3b]
  [bt] (8) /anaconda/envs/azureml_py36/bin/python(+0x199c0e) [0x564f6a621c0e]


Traceback:
  File "_model_download_utilities.py", line 177, in _load_automl_model
    fitted_model = pickle.load(model_file)  # type: Optional[Any]
  File "core.py", line 1088, in __setstate__
    _LIB.XGBoosterUnserializeFromBuffer(handle, ptr, length))
  File "core.py", line 189, in _check_call
    raise XGBoostError(py_str(_LIB.XGBGetLastError()))

ExceptionTarget: Unspecified
2021-03-31 20:48:51.803 - CRITICAL - 4431 - azureml.train.automl._model_download_utilities.log_traceback:224 - Type: IncompatibleOrMissingDependency
Class: ConfigException
Message: ConfigException:
	Message: The model you attempted to retrieve requires 'xgboost' to be installed at '==0.90'. You have 'xgboost==1.3.3', please reinstall 'xgboost==0.90' (e.g. `pip install xgboost==0.90`) and rerun the previous command.
	InnerException: XGBoostError: [20:48:51] /mnt/xgboost/src/learner.cc:922: Check failed: header == serialisation_header_: 

  If you are loading a serialized model (like pickle in Python) generated by older
  XGBoost, please export the model by calling `Booster.save_model` from that version
  first, then load it back in current version.  There's a simple script for helping
  the process. See:

    https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html

  for reference to the script, and more details about differences between saving model and
  serializing.


Stack trace:
  [bt] (0) /anaconda/envs/azureml_py36/lib/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x7c) [0x7fc699ba264c]
  [bt] (1) /anaconda/envs/azureml_py36/lib/libxgboost.so(xgboost::LearnerIO::Load(dmlc::Stream*)+0x66b) [0x7fc699cacf0b]
  [bt] (2) /anaconda/envs/azureml_py36/lib/libxgboost.so(XGBoosterUnserializeFromBuffer+0x5e) [0x7fc699b967fe]
  [bt] (3) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x69dd) [0x7fc7a48729dd]
  [bt] (4) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x6067) [0x7fc7a4872067]
  [bt] (5) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fc7a488aede]
  [bt] (6) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fc7a488b915]
  [bt] (7) /anaconda/envs/azureml_py36/bin/python(_PyObject_FastCallDict+0x8b) [0x564f6a599e3b]
  [bt] (8) /anaconda/envs/azureml_py36/bin/python(+0x199c0e) [0x564f6a621c0e]


	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "The model you attempted to retrieve requires 'xgboost' to be installed at '==0.90'. You have 'xgboost==1.3.3', please reinstall 'xgboost==0.90' (e.g. `pip install xgboost==0.90`) and rerun the previous command.",
        "target": "get_output",
        "inner_error": {
            "code": "NotSupported",
            "inner_error": {
                "code": "IncompatibleOrMissingDependency"
            }
        },
        "reference_code": "910310e6-2433-40cd-b597-9ec2950bc1d8"
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "_model_download_utilities.py", line 91, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 281, in _load_automl_model
    ) from e

ExceptionTarget: get_output
2021-03-31 20:48:51.803 - INFO - 4431 - azureml.train.automl._model_download_utilities._log_activity:93 - ActivityCompleted: Activity=DownloadModel, HowEnded=Failure, Duration=489.54[ms]
2021-03-31 20:48:51.804 - CRITICAL - 4431 - azureml.train.automl.run.log_traceback:224 - Type: IncompatibleOrMissingDependency
Class: ConfigException
Message: ConfigException:
	Message: The model you attempted to retrieve requires 'xgboost' to be installed at '==0.90'. You have 'xgboost==1.3.3', please reinstall 'xgboost==0.90' (e.g. `pip install xgboost==0.90`) and rerun the previous command.
	InnerException: XGBoostError: [20:48:51] /mnt/xgboost/src/learner.cc:922: Check failed: header == serialisation_header_: 

  If you are loading a serialized model (like pickle in Python) generated by older
  XGBoost, please export the model by calling `Booster.save_model` from that version
  first, then load it back in current version.  There's a simple script for helping
  the process. See:

    https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html

  for reference to the script, and more details about differences between saving model and
  serializing.


Stack trace:
  [bt] (0) /anaconda/envs/azureml_py36/lib/libxgboost.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x7c) [0x7fc699ba264c]
  [bt] (1) /anaconda/envs/azureml_py36/lib/libxgboost.so(xgboost::LearnerIO::Load(dmlc::Stream*)+0x66b) [0x7fc699cacf0b]
  [bt] (2) /anaconda/envs/azureml_py36/lib/libxgboost.so(XGBoosterUnserializeFromBuffer+0x5e) [0x7fc699b967fe]
  [bt] (3) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x69dd) [0x7fc7a48729dd]
  [bt] (4) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/../../libffi.so.6(+0x6067) [0x7fc7a4872067]
  [bt] (5) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7fc7a488aede]
  [bt] (6) /anaconda/envs/azureml_py36/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13915) [0x7fc7a488b915]
  [bt] (7) /anaconda/envs/azureml_py36/bin/python(_PyObject_FastCallDict+0x8b) [0x564f6a599e3b]
  [bt] (8) /anaconda/envs/azureml_py36/bin/python(+0x199c0e) [0x564f6a621c0e]


	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "The model you attempted to retrieve requires 'xgboost' to be installed at '==0.90'. You have 'xgboost==1.3.3', please reinstall 'xgboost==0.90' (e.g. `pip install xgboost==0.90`) and rerun the previous command.",
        "target": "get_output",
        "inner_error": {
            "code": "NotSupported",
            "inner_error": {
                "code": "IncompatibleOrMissingDependency"
            }
        },
        "reference_code": "910310e6-2433-40cd-b597-9ec2950bc1d8"
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 704, in get_output
    fitted_model = _download_automl_model(curr_run, model_name)
  File "_model_download_utilities.py", line 91, in _download_automl_model
    model = _load_automl_model(model_path, suffix)
  File "_model_download_utilities.py", line 281, in _load_automl_model
    ) from e

ExceptionTarget: get_output
2021-03-31 20:48:51.804 - INFO - 4431 - azureml.train.automl.run._log_activity:93 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=715.62[ms]
